version: "3.8"


services:

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    restart: always
    command: ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 80:8000
    volumes:

      - app_volume:/opt/docker-volumes/app
volumes:
  app_volume:
