version: "3.8"


services:

  app:
    build: .
    command: ["poetry", "run" ,"gunicorn", "quotesapp.wsgi:application", "--bind", "0.0.0.0:80"]
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    expose:
      - "80"

  server:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - ./server/nginx.conf:/etc/nginx/nginx.conf

    expose:
      - "80"
volumes:
  static_volume:
  media_volume: