# Generated by Django 4.2.7 on 2023-11-22 05:37

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='id',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=6, max_length=6, prefix='', primary_key=True, serialize=False),
        ),
    ]
