# Generated by Django 4.2.7 on 2023-11-20 15:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='author'),
        ),
    ]
