# Generated by Django 4.2.7 on 2023-11-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_topic_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_slug',
        ),
    ]
