# Generated by Django 4.2.7 on 2023-11-22 15:17

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_topic_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='Topics/Tags: '),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='topic', unique=True),
        ),
    ]
