# Generated by Django 4.2.7 on 2023-11-22 15:17

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_topic_topic_alter_topic_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.CharField(max_length=50, unique=True, verbose_name='Author: '),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='author', unique=True),
        ),
    ]
