# Generated by Django 4.2.7 on 2023-11-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_author_author_alter_author_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.author', to_field='author_slug', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic', to_field='topic_slug', verbose_name='Topics/Tags'),
        ),
    ]
