# Generated by Django 4.2.7 on 2023-11-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_simplecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplecontact',
            name='elaboration',
            field=models.TextField(default='N/A', verbose_name='Please Elaborate'),
            preserve_default=False,
        ),
    ]
