# Generated by Django 4.2.7 on 2023-11-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_simplecontact_elaboration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplecontact',
            name='elaboration',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
