# Generated by Django 4.2.7 on 2023-11-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_simplecontact_elaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image_1',
            field=models.ImageField(default='default.png', upload_to='quoteimg', verbose_name='Image 1:'),
        ),
        migrations.AddField(
            model_name='quote',
            name='image_2',
            field=models.ImageField(default='default.png', upload_to='quoteimg', verbose_name='Image 2:'),
        ),
        migrations.AddField(
            model_name='quote',
            name='image_3',
            field=models.ImageField(default='default.png', upload_to='quoteimg', verbose_name='Image 3:'),
        ),
        migrations.AddField(
            model_name='quote',
            name='image_4',
            field=models.ImageField(default='default.png', upload_to='quoteimg', verbose_name='Image 4:'),
        ),
        migrations.AddField(
            model_name='quote',
            name='image_5',
            field=models.ImageField(default='default.png', upload_to='quoteimg', verbose_name='Image 5:'),
        ),
    ]
