# Generated by Django 4.2.7 on 2024-04-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_quote_image_1_quote_image_2_quote_image_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='image_5',
        ),
    ]
