# Generated by Django 5.0.6 on 2024-05-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_quote_image_1_remove_quote_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='images',
            field=models.JSONField(default=list, verbose_name='Images'),
        ),
    ]
