name: Building QuotesApp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12' 
      # - run: |
      #     pipx install poetry


      # - name: Install dependencies
      #   run: poetry install

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          poetry install
          poetry run python3 manage.py tailwind install --settings=quotesapp.settings.prod
          poetry run python3 manage.py tailwind build --settings=quotesapp.settings.prod

      - name: Build Static Site
        run: poetry run python3 manage.py distill-local public --collectstatic --force --settings=quotesapp.settings.prod

      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-cli@v2
        id: netlify
        with:
          args: 'deploy --json --dir \"./public\" --message \"draft [${{ github.sha }}]\"'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}